# Only for Reference - Need to cosnidere Direct/Regular and Growth/IDCW

In [1]:
import pandas as pd

In [3]:
mf_prices_df = pd.read_csv(r"data\mf_scheme_mapping_master.csv")
mf_prices_df.head(2)

,Scheme Code,ISIN Div Payout/ ISIN Growth,ISIN Div Reinvestment,Scheme Name,Plan,Option,Net Asset Value,Date
0,135762,INF846K01WO1,-,Axis Children's Fund,Direct Plan,Growth Option,30.3228,2026-09-04
1,135765,INF846K01WP8,-,Axis Children's Fund,Direct Plan,IDCW Option,27.9328,2026-09-04

In [4]:
mf_tracker = pd.read_csv(r"C:\Users\nskar\Downloads\Asset Tracker - MF Tracker Data.csv")
mf_tracker.head(2)

,SNo,Fund SNo,Holding,Vendor,Active,Name,Direct /\nRegular,Type,Category,Date,...,Profit,Absolute Profit %,#Days,# Years,Yearly %,XIRR,Unnamed: 28,Ticker Google Finance,AMFI Scheme Code,Comments
0,1.0,NaN,PhonePe,Axis,N,Axis ELSS Tax Saver Fund,Regular,Growth,Equity,6-Apr-21,...,"3,061",61.21,1980,5.0,12.24,10.02%,9.20%,MUTF_IN:AXIS_ELSS_TAX_1UV99TD,112322.0,Switched to Direct
1,15.0,NaN,DSP,DSP,Y,DSP ELSS Tax Saver Fund,Direct,Growth,Equity,3-Apr-24,...,232,23.23,887,2.0,11.61,11.01%,8.98%,MUTF_IN:DSP_ELSS_TAX_F8PE7V,119242.0,Switched to DSP Nifty 50 18-Aug-26

In [5]:
mf_tracker = mf_tracker[mf_tracker['Active'] == 'Y']

In [6]:
funds = list(mf_tracker['Name'].unique())

In [7]:
scheme_code_map = dict()

In [8]:
int(mf_prices_df[mf_prices_df['Scheme Name'] == "Axis Children's Fund"].iloc[0]['Scheme Code'])

135762

In [9]:
for f in funds:
    try:
        tmp_code = int(mf_prices_df[mf_prices_df['Scheme Name'] == f].iloc[0]['Scheme Code'])
        scheme_code_map[f] = tmp_code
    except Exception as e:
        print(f"{f} - fund not mapped")

Axis ELSS Tax Saver Fund - fund not mapped
DSP Mid Cap Fund - fund not mapped
DSP Multi-Asset Allocation Fund - fund not mapped
Axis MultiCap Fund - fund not mapped
Axis Retirement Savings Fund - Aggressive Plan - fund not mapped
DSP Silver ETF FoF - fund not mapped

In [10]:
mapper = {
    "DSP Mid Cap Fund" : "DSP Midcap Fund",
    "DSP Multi-Asset Allocation Fund" : "DSP Multi Asset Allocation Fund",
    "DSP Silver ETF FoF" : "DSP Silver ETF Fund of Fund",
    "Axis ELSS Tax Saver Fund" : "Axis ELSS- Tax Saver Fund",
    "Axis MultiCap Fund" : "Axis Multicap Fund",
    "Axis Retirement Savings Fund - Aggressive Plan" : "Axis Retirement Fund - Aggressive Plan"
}

In [11]:
scheme_code_map = dict()

In [12]:
for f in funds:
    try:
        f_alt = mapper.get(f,f)
        if f in mf_prices_df['Scheme Name'].values:
            tmp_code = int(mf_prices_df[mf_prices_df['Scheme Name'] == f].iloc[0]['Scheme Code'])
        elif f_alt in mf_prices_df['Scheme Name'].values:
            tmp_code = int(mf_prices_df[mf_prices_df['Scheme Name'] == f_alt].iloc[0]['Scheme Code'])
        
        scheme_code_map[f] = tmp_code
        del tmp_code
    except Exception as e:
        
        print(f"{f} - fund not mapped")

In [13]:
scheme_code_map

{'DSP ELSS Tax Saver Fund': 119242,
 'DSP Flexi Cap Fund': 119076,
 'Axis ELSS Tax Saver Fund': 120503,
 'DSP Gold ETF Fund of Fund': 152183,
 'DSP Mid Cap Fund': 119071,
 'DSP Multi-Asset Allocation Fund': 152056,
 'Axis MultiCap Fund': 149383,
 'Axis Nifty 100 Index Fund': 147666,
 'Axis Nifty 50 Index Fund': 149373,
 'DSP Nifty 50 Equal Weight Index Fund': 141877,
 'DSP Nifty 50 Index Fund': 146376,
 'Axis Retirement Savings Fund - Aggressive Plan': 147825,
 'DSP Silver ETF FoF': 153487,
 'DSP Small Cap Fund': 119212}

In [15]:
a = [v for k,v in scheme_code_map.items()]
a.sort()
a

[119071,
 119076,
 119212,
 119242,
 120503,
 141877,
 146376,
 147666,
 147825,
 149373,
 149383,
 152056,
 152183,
 153487]

In [16]:
# 104773
# 112322
# 119071
# 119076
# 119212
# 119242
# 120503
# 141877
# 146376
# 147666
# 147825
# 149373
# 149383
# 152056
# 152183
# 153487